export default [
    {
        value:'yi',
        label:'一宿',
        children:[{
            value:'first',
            label:'一楼'
        },
        {
            value:'second',
            label:'二楼'
        },
        {
            value:'third',
            label:'三楼'
        },
        {
            value:'forth',
            label:'四楼'
        },
        {
            value:'fifth',
            label:'五楼'
        },
        {
            value:'sixth',
            label:'六楼'
        }
    ]
    },
    {
        value:'er',
        label:'二宿',
        children:[{
            value:'first',
            label:'一楼'
        },
        {
            value:'second',
            label:'二楼'
        },
        {
            value:'third',
            label:'三楼'
        },
        {
            value:'forth',
            label:'四楼'
        },
        {
            value:'fifth',
            label:'五楼'
        },
        {
            value:'sixth',
            label:'六楼'
        }
    ]
    },
    {
        value:'san',
        label:'三宿',
        children:[{
            value:'first',
            label:'一楼'
        },
        {
            value:'second',
            label:'二楼'
        },
        {
            value:'third',
            label:'三楼'
        },
        {
            value:'forth',
            label:'四楼'
        },
        {
            value:'fifth',
            label:'五楼'
        },
        {
            value:'sixth',
            label:'六楼'
        }
    ]
    },
    {
        value:'si',
        label:'四宿',
        children:[{
            value:'first',
            label:'一楼'
        },
        {
            value:'second',
            label:'二楼'
        },
        {
            value:'third',
            label:'三楼'
        },
        {
            value:'forth',
            label:'四楼'
        },
        {
            value:'fifth',
            label:'五楼'
        },
        {
            value:'sixth',
            label:'六楼'
        }
    ]
    },
    {
        value:'wu',
        label:'五宿',
        children:[{
            value:'first',
            label:'一楼'
        },
        {
            value:'second',
            label:'二楼'
        },
        {
            value:'third',
            label:'三楼'
        },
        {
            value:'forth',
            label:'四楼'
        },
        {
            value:'fifth',
            label:'五楼'
        },
        {
            value:'sixth',
            label:'六楼'
        }
    ]
    },
    {
        value:'liu',
        label:'六宿',
        children:[{
            value:'first',
            label:'一楼'
        },
        {
            value:'second',
            label:'二楼'
        },
        {
            value:'third',
            label:'三楼'
        },
        {
            value:'forth',
            label:'四楼'
        },
        {
            value:'fifth',
            label:'五楼'
        },
        {
            value:'sixth',
            label:'六楼'
        }
    ]
    },
    {
        value:'qi',
        label:'七宿',
        children:[{
            value:'first',
            label:'一楼'
        },
        {
            value:'second',
            label:'二楼'
        },
        {
            value:'third',
            label:'三楼'
        },
        {
            value:'forth',
            label:'四楼'
        },
        {
            value:'fifth',
            label:'五楼'
        },
        {
            value:'sixth',
            label:'六楼'
        }
    ]
    },
    {
        value:'ba',
        label:'八宿',
        children:[{
            value:'first',
            label:'一楼'
        },
        {
            value:'second',
            label:'二楼'
        },
        {
            value:'third',
            label:'三楼'
        },
        {
            value:'forth',
            label:'四楼'
        },
        {
            value:'fifth',
            label:'五楼'
        },
        {
            value:'sixth',
            label:'六楼'
        }
    ]
    },
    {
        value:'jiu',
        label:'九宿',
        children:[{
            value:'first',
            label:'一楼'
        },
        {
            value:'second',
            label:'二楼'
        },
        {
            value:'third',
            label:'三楼'
        },
        {
            value:'forth',
            label:'四楼'
        },
        {
            value:'fifth',
            label:'五楼'
        },
        {
            value:'sixth',
            label:'六楼'
        }
    ]
    }
]