export const orderlist = [{
    id:1,
    type:'快递代取',
    status:'悬赏中',
    issue:'张三',
    date:'1小时前',
    description:'大件',
    notice:'注意：请尽快送达',
    prize:'10'
  },
  {
    id:2,
    type:'超市代购',
    status:'已完成',
    issue:'李四',
    date:'2小时前',
    description:'瓶装饮用水',
    notice:'注意：请尽快送达',
    prize:'5'
  },
  {
    id:3,
    type:'外卖代购',
    status:'待接单',
    issue:'王五',
    date:'3小时前',
    description:'麻辣烫',
    notice:'注意：请尽快送达',
    prize:'15'
  },
  {
   id:4,
    type:'小吃街代购',
    status:'待接单',
    issue:'王小义',
    date:'4小时前',
    description:'香辣鸡腿堡',
    notice:'注意：请尽快送达',
    prize:'20'
  }
  ]
